<?php
/**
 * Hook implementations for metatag module.
 */

/**
 * Implements hook_page_attachments().
 *
 * Load all meta tags for this page.
 */
function metatag_page_attachments(array &$attachments) {
  $metatags = array();
  $metatag_context = entity_load('metatag_context', 'global');

  if (!empty($metatag_context)) {
    if (!empty($metatag_context->get('description'))) {
      $metatags['description'] = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'description',
          'content' => \Drupal::token()->replace($metatag_context->get('description')),
        ),
      );
    }
    if (!empty($metatag_context->get('abstract'))) {
      $metatags['abstract'] = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'abstract',
          'content' => \Drupal::token()->replace($metatag_context->get('abstract')),
        ),
      );
    }
    if (!empty($metatag_context->get('keywords'))) {
      $metatags['keywords'] = array(
        '#tag' => 'meta',
        '#attributes' => array(
          'name' => 'keywords',
          'content' => \Drupal::token()->replace($metatag_context->get('keywords')),
        ),
      );
    }
  }

  if (!empty($metatags)) {
    foreach ($metatags as $key => $value) {
      $attachments['#attached']['html_head'][] = [$value, $key];
    }
  }
}

/**
 * Implements hook_preprocess_html().
 */
function metatag_preprocess_html(array &$variables) {
  // Alter the page title.
  $metatag_global = entity_load('metatag_context', 'global');
  if (!empty($metatag_global)) {
    $title = $metatag_global->get('title');
    if (!empty($title)) {
      $processed_title = \Drupal::token()->replace($title);
      $variables['head_title'] = array('metatag' => $processed_title);
    }
  }
}
