<?php
/**
 * Install hooks for metatag module.
 */

use Drupal\metatag\Entity\MetatagContext;

/**
 * Implements hook_install().
 */
function metatag_install() {
  // Create the global metatag.
  $metatag_defaults = \Drupal::config('metatag.global');
  $entity = MetatagContext::create(array(
    'id' => 'global',
    'label' => 'Global',
    'title' => $metatag_defaults->get('title'),
  ))->save();
}
