metatag.metatag_context.*:
  type: config_entity
  label: 'Metatag'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Type'
    uuid:
      type: string
    title:
      type: string
      label: 'Page title'
    description:
      type: string
      label: 'Description'
    abstract:
      type: string
      label: 'Abstract'
    keywords:
      type: string
      label: 'Keywords'
