metatag.metatag_context.*:
  type: config_entity
  label: 'Metatag'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Type'
    tags:
      type: sequence
      label: 'Tags'
      sequence:
        type: metatag.metatag_tag.[plugin_id]
